--
-- PostgreSQL database dump
--

-- Dumped from database version 16.0 (Debian 16.0-1.pgdg120+1)
-- Dumped by pg_dump version 16.3 (Ubuntu 16.3-1.pgdg22.04+1)

-- Started on 2024-05-16 14:53:44 -04

--
-- TOC entry 248 (class 1259 OID 24898)
-- Name: configuracion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.configuracion (
    id integer NOT NULL,
    cantidad_vocablos integer DEFAULT 0 NOT NULL,
    categorias_id integer[] NOT NULL,
    tipo_pregunta text DEFAULT 'imagen'::text NOT NULL,
    tipo_respuesta text DEFAULT 'texto'::text NOT NULL
);


ALTER TABLE public.configuracion OWNER TO postgres;

--
-- TOC entry 247 (class 1259 OID 24897)
-- Name: configuracion_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.configuracion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.configuracion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3423 (class 0 OID 24898)
-- Dependencies: 248
-- Data for Name: configuracion; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.configuracion VALUES (3, 52, '{}', 'imagen', 'texto');
INSERT INTO public.configuracion VALUES (4, 34, '{}', 'imagen', 'texto');
INSERT INTO public.configuracion VALUES (5, 50, '{}', 'imagen', 'texto');
INSERT INTO public.configuracion VALUES (6, 15, '{}', 'imagen', 'texto');
INSERT INTO public.configuracion VALUES (0, 32, '{}', 'video', 'imagen');
INSERT INTO public.configuracion VALUES (1, 60, '{}', 'video', 'imagen');
INSERT INTO public.configuracion VALUES (2, 50, '{}', 'imagen', 'texto');


--
-- TOC entry 3429 (class 0 OID 0)
-- Dependencies: 247
-- Name: configuracion_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.configuracion_id_seq', 1, false);


--
-- TOC entry 3278 (class 2606 OID 24907)
-- Name: configuracion configuracion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.configuracion
    ADD CONSTRAINT configuracion_pkey PRIMARY KEY (id);


-- Completed on 2024-05-16 14:53:56 -04

--
-- PostgreSQL database dump complete
--

